### ISSUE TITLE
[Question] How make a reset ?

### ISSUE THREAD

**Issue by gsegit** [iakmds/buhocms#1]
Hello ;D
At first, thats is a very intrested project ;D And now to my question, how I can make a new start with the program ? So that I can make  a new Site ?

Greetings

Bogus

**Comment by iakmds** [comment]
Hi @gsegit, thanks for the first issue :smile: 

There are 2 ways you can create a new site:
- You click on the "File" tab on the menu bar **(1)** and choose "Create site" **(2)**
- You go to the settings and click the "Create site" button **(3)**

![create-site](https://user-images.githubusercontent.com/111225446/219801208-5b9500f0-e01e-48fa-916c-b4e1e9beec2e.png)

I hope this helped you. Let me know if I can close this issue or if you have any further questions!

**Comment by gsegit** [comment]
OK, I have the problem, that I see nothing in the site middle and when I go to create site, then comes a message that I must save the site, but I could not this ;D

So I have make a screenshot ;D I hope you can fix this ;D Oh I use Linux Mint too ;D
![Bildschirmfoto vom 2023-02-18 01-22-35](https://user-images.githubusercontent.com/104396251/219820790-83b6849b-f2bd-4fea-8c39-a412674d549b.png)

**Comment by iakmds** [comment]
Your profile says you're from Germany :smiley: 

Also: Das sieht tatsächlich nach einem Bug aus, den ich beheben müsste! Eigentlich müsste da der Text stehen "Keine Datei ausgewählt". Um ihn erstmal zu umgehen, könntest du einen neuen Post/Artikel erstellen, und falls der Dialog mit "ungespeicherten Änderungen" erscheint auf "Nicht speichern" drücken. Jetzt müsste man etwas sehen und den Post bearbeiten können :+1: 

Um mir beim Beheben des Bugs zu helfen, wäre es sehr hilfreich, wenn du mir die Schritte erklären könntest, die zum Bug führen, z.B. 
1. Auf "Neue Seite erstellen" klicken
3. "Daten eingeben und erstellen"
4. Fehler

**Comment by gsegit** [comment]
Also das fing damit eigentlich an, das ich das theme nicht runterladen konnte, bzw. wurde nur das redraw Zeichen angezeigt. In dem Ordner selbst ist aber das Theme enthalten. Dann hab ich das Programm neu gestartet und hab nur nur noch deses Bild vor mir, das was ich gepostet hab. 

OK, ich hab mal versucht nun eine neue Seite zu erstellen, da kommt eine Dialogbox mit .... Rückgängig machen ---- Speichern.
Wenn ich auf Speichern gehe, passiert nichts, bei Rückgängig machen kriege ich nur die Meldung ob ich es wirklich es will, wenn ich bestätige, passiert auch nichts. 

Das ist eigentlch alles was ich dazu schreiben kann, vielleicht wäre es gut wenn ein Terminal unten auftauchen würde wo man die einzelnen Schritte nochmal nachlesen kann bzw, das was dann geschieht und vielleicht auch ein Logfile, wobei dieses man in einer Config datei ja ausklammern könnte, so das diese nicht erzeugt wird,. Halt als Bugreport für dich, denke das würde es um einiges einfach machen ;D

Das ganze auf deutsch zu schreiben ist schon um einiges leichter.  Biste im Matrix unterwegens ? Mich würde auch intressieren, wo du auf so eine Idee gekommen bist ? Ach haste dein Projekt im Forum von Hugo gepostet ? Denke da würde doch einige intressse haben ;D

Tschöö

Bogus

**Comment by iakmds** [comment]
> Also das fing damit eigentlich an, das ich das theme nicht runterladen konnte, bzw. wurde nur das redraw Zeichen angezeigt. In dem Ordner selbst ist aber das Theme enthalten. Dann hab ich das Programm neu gestartet und hab nur nur noch deses Bild vor mir, das was ich gepostet hab.

> OK, ich hab mal versucht nun eine neue Seite zu erstellen, da kommt eine Dialogbox mit .... Rückgängig machen ---- Speichern.
Wenn ich auf Speichern gehe, passiert nichts, bei Rückgängig machen kriege ich nur die Meldung ob ich es wirklich es will, wenn ich bestätige, passiert auch nichts.

Danke für all die Infos. Und schade, dass bei dir nicht alles funktioniert hat :/ Eine letzte Frage, sind bei dir Hugo und git korrekt installiert?

> Das ist eigentlch alles was ich dazu schreiben kann, vielleicht wäre es gut wenn ein Terminal unten auftauchen würde wo man die einzelnen Schritte nochmal nachlesen kann bzw, das was dann geschieht und vielleicht auch ein Logfile, wobei dieses man in einer Config datei ja ausklammern könnte, so das diese nicht erzeugt wird,. Halt als Bugreport für dich, denke das würde es um einiges einfach machen ;D

Tatsächlich ist ein "Terminal output" in der Roadmap geplant :+1:

> Das ganze auf deutsch zu schreiben ist schon um einiges leichter. Biste im Matrix unterwegens ? Mich würde auch intressieren, wo du auf so eine Idee gekommen bist ? Ach haste dein Projekt im Forum von Hugo gepostet ? Denke da würde doch einige intressse haben ;D

Auf Matrix leider nicht. Die Idee kam mir, als ich selber nicht ganz mit dem Hugo/Static Site Generator Workflow zufrieden war, einfach weil ich oft das Terminal für simple Sachen benutzen musste, oder auch das Suchen nach den Dateien in den Ordnern, um dann im Text Editor den Artikel und die Front matter-Felder zu bearbeiten... Dann habe ich natürlich zuerst online nach Hugo GUIs gesucht, da kam ich auf https://gohugo.io/tools/frontends/. Davon habe ich einige probiert, aber entweder waren sie nicht das, wonach ich gesucht habe (eine Art Desktop-Editor), oder aber sie wurden seit Jahren nicht geupdated... Also dachte ich, warum nicht selber einen erstellen :smile:  

Und danke für die Idee, das ganze im Forum zu posten. Werde ich auf jeden Fall demnächst machen :+1:

**Comment by gsegit** [comment]
Sooo, schade das du nicht auf Matrix bist, dann wäre das mit dem Feedback geben ein wenig kürzer *gg

Aber ich kann dir sagen, das es wohl kein Bug ist, eher wohl ein Benutzerfehler *gg Hab die App auf meinen Lappi probiert, da hab ich auch Hugo drauf und ja Hugo ist auf auf meinen PC richtig installiert, nehme immer die deb binarie ;D 
Da hat das mit dem Theme runterladen geklappt,  weiss nicht was beim erstenmal nicht klappte, aber deine App funzt ;D 
Nur ein art neustart Option wäre nicht schlecht, damit man das ganze nochmal probieren kann, also die Anfangsprozedur ;D

Lass mich raten, du bist ein Schüler und machst grade dein ABI ? *gg

Bin genauso ein wenig gefrustet von dem Workflow, auch weil ich älterer Jahrgang bin und immer wieder dran zu erinnern, wie das ganze funzt ist nicht grade leicht ;D

Jedenfalls danke für deine Idee und werde es weiter testen ;D

Tschöö

Bogus

**Comment by iakmds** [comment]
Abi habe ich bereits ;)
Eine Neustart Option ist schon vorhanden (2 Möglichkeiten):
- In den Einstellungen setzt du das Programm zurück (samt Thema, Sprachauswahl, aktueller Seitenpfad, etc.) **(1)**
- Ganz unten in den Einstellungen klickst du auf "Mehr" **(2)** und wählst "Einführungsseite" **(3)**

![neustart](https://user-images.githubusercontent.com/111225446/219900926-3a645c39-978f-460a-8d7a-9b1b51d4dc1e.png)

**Comment by gsegit** [comment]
Supi, damit ist meine Frage ja beantwortet ;D Und kann diesen Post schliessen ;D
