### ISSUE TITLE
[Question] Kernel required

### ISSUE THREAD

**Issue by Aliko974** [iakmds/buhocms#15]
Hello everyone,
i'm not computer specialist, so my technical knowledges are not so far to empty...

I have installed Jekyll on Linux (by apt install jekyll) and i also installed Buhocms, but i have this message when i want to create a new website :

`Exit code 1:
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in require':
cannot load such file - mercenary (LoadError)
from /usr/lib/ruby/2.7.0/ruby...`

Have you an idea what's the problem and if there's a solutions, please ?

Thank you so much for your help.

Best regards,
Steve

**Comment by Aliko974** [comment]
And also, i have seen this message when i want to start the live server :

`ShellException(hugo server, error: ProcessException: No file or folder of this type
Command: /snap/bin/hugo server, workingDirectory: my folder way`

Thank for your help.

**Comment by Aliko974** [comment]
Hello iakmds,
Thank's for your response.

I will respond to your message probably tomorow because i'm tired. I'm going to sleep for now.

**Comment by Aliko974** [comment]
> Hello there, thanks for the issue,
> 
> regarding the first problem: Could you try installing Jekyll as described in its documentation https://jekyllrb.com/docs/? I had some issues too when I used the `sudo apt install jekyll` aproach.
> 
> In your second error message, the `workingDirectory` says `my folder way`, but it should be a folder directory instead, like `/home/user/Desktop/my-hugo-website`
> 
> Last note, did I get it right that the first error relates to Jekyll and the second one to Hugo? Or did you use Jekyll only? Let me know how all went.

Hello iakmds,
i have made what you propose to me... But there's too much problems.

I'm not a specialist, so i will drop out this tool and i will looking for others solutions.

Thanks a lot for your help.

**Comment by iakmds** [comment]
I'm sorry I couldn't help. I understand, thank you for trying out BuhoCMS!
