### ISSUE TITLE
Eleventy support

### ISSUE THREAD

**Issue by xplosionmind** [iakmds/buhocms#17]
It would be so nice to consider supporting Eleventy!

**Comment by iakmds** [comment]
Thank you for the request! 
In fact, it looks like adding support is going to be very straightforward. I will start working on it :+1:

**Comment by iakmds** [comment]
Hey @xplosionmind,
Eleventy support was added via [v0.7.0](https://github.com/iakmds/buhocms/releases/tag/v0.7.0)! Let me know what you think of it :+1:

**Comment by xplosionmind** [comment]
Hell yeah! Thanks!

I am waiting for the Flathub update to appear. I will let you know. All the best!

**Comment by xplosionmind** [comment]
> Any updates so far? :smile: 

Hi! I am very sorry but I realized that my use case is definitely too complex to use a CMS… I am sorry but I cannot help you with this.

**Comment by iakmds** [comment]
I see, no problem. Now that 11ty support is added though, can we close this issue?
