### ISSUE TITLE
[BUG] ShellException(hugoserver, exitCode 255 - Screenshot Inside

### ISSUE THREAD

**Issue by gsegit** [iakmds/buhocms#19]
Hallo ;D
Hab ein Bug in der aktuellen 0.62 entdeckt. wenn ich den Hugoserver starte kommt diese Meldung siehe Screenshot
![Bildschirmfoto vom 2023-04-30 22-00-59](https://user-images.githubusercontent.com/104396251/235374405-2759b0d6-fc6f-483d-b4df-25444f6a7294.png)

Tschöö
Gerriet

**Comment by hugo-sid** [comment]
English translation of the above comment:

Hi ;D
I discovered a bug in the current 0.6.2 version. When I start the Hugo server, the following message appears (see screenshot).

Bye
Gerriet

**Comment by gsegit** [comment]
Der Bug ist bei der aktuellen Version nicht mehr aufgetreten ;D Damit kanste ihn schliessen bzw., ich mache es ;D
