### ISSUE TITLE
[feedback] Opening website doesn't work

### ISSUE THREAD

**Issue by gsegit** [iakmds/buhocms#2]
Halllo ;D
So ich denke nun hab ich aber einen Bug entdeckt, hab eine Seite einlesen bzw. öffnen wollen. Die Seite liegt übrigens bei Codeberg.de
https://codeberg.org/vollkorntomate/vollkorntomate.de

Es kann auch daran liegen, das deine App die Config nicht einlesen kann, so ist meine Vermutung bzw. das die Seite ein submodul benutzt. Damit hatte ich beim erstenmal bei dem Code auch meine Probleme.

Am besten du versuchst es selbst mal ;D

Was ich noch erwähnen wollte, es ist wohl so, das die Theme nicht immer vorhanden ist, hatte einige male beim öffnen der Seite im Browser ein Page not found, das könnte darauf hinweisen das das Theme nicht richtig eingelesen wurde.

Tschöö

Bogus

**Comment by iakmds** [comment]
Hab anscheinend die Nachricht nicht abgeschickt... schreibe es nochmal:

> Es kann auch daran liegen, das deine App die Config nicht einlesen kann, so ist meine Vermutung bzw. das die Seite ein submodul benutzt. Damit hatte ich beim erstenmal bei dem Code auch meine Probleme.

Habe es auch mit der Webseite probiert. Das Öffnen der Seite hat funktioniert, jedoch konnte ich den Server nicht korrekt starten. Wenn ich im Terminal eingebe "hugo server", kommt eine Fehlermeldung, dass kein git im Ordner gefunden wurde. Als ich git initialisiert habe, war kein "master" branch zu finden. Ich weiß noch nicht, ob das ganze mit dem Programm oder mit der Hugo Seite + Git zu tun hat... Und Submodule support kommt in Zukunft :+1:

> Was ich noch erwähnen wollte, es ist wohl so, das die Theme nicht immer vorhanden ist, hatte einige male beim öffnen der Seite im Browser ein Page not found, das könnte darauf hinweisen das das Theme nicht richtig eingelesen wurde.

Welchen Dateityp verwendest du, eine config.toml, config.yaml oder config.json?

**Comment by gsegit** [comment]
Ja bei dem code der hugo seite hatte ich zuerst auch meine probleme, wenn du in dem repo bei issues schaust, dann siehste das ich mich auch eingebracht hab 😎 kann ich denn normal über die console die submodule einlesen ? 

Ich nutze meist das yaml, ist es denn wichtig was man für ein format nutze ?

**Comment by iakmds** [comment]
> Ja bei dem code der hugo seite hatte ich zuerst auch meine probleme, wenn du in dem repo bei issues schaust, dann siehste das ich mich auch eingebracht hab sunglasses kann ich denn normal über die console die submodule einlesen ?

Das müsste funktionieren.

> Ich nutze meist das yaml, ist es denn wichtig was man für ein format nutze ?

Es könnte sein, dass momentan die Logik für config Dateien (theme=X schreiben) nur bei .toml funktioniert, werde ich nochmal testen.

Bezüglich diesem Issue, da wir mehrere Sachen besprochen haben, trifft der Titel "Seite öffnen funktioniert nicht/Opening website doesn't work" noch zu, oder würdest du ihn auf ein Problem ändern, das am wahrscheinlichsten mit BuhoCMS zu tun hat?

**Comment by gsegit** [comment]
Stimmt, hast eigentlich recht, aber weiss nicht was ich da schreiben sollte. Sonst wenn du magst, änder du doch die Überschrift ;D 

Hab übrigens mal verschucht mit dem ChatGT ein Frontend schreiben zulassen, naja sagen mal den Anfang von einem *gg
