### ISSUE TITLE
[Feedback] German translation: Seite einlesen statt öffnen

### ISSUE THREAD

**Issue by gsegit** [iakmds/buhocms#3]
Hab ein Vorschlag, nämlich statt Seite einlesen statt öffnen. Und das Artikel erstellen unter Datei setzen, ich verwechsel Seite erstelle mmit Artikel erstellen *gg

**Comment by iakmds** [comment]
Ich glaube, ich ändere einfach Seite in Webseite, das macht auf jeden Fall mehr Sinn.

Das mit der Menüleiste macht ebenfalls Sinn :+1:

**Comment by iakmds** [comment]
So würde das dann in der nächsten Version aussehen :smile: 

![menubar](https://user-images.githubusercontent.com/111225446/219943277-d5d51c12-6217-4c5b-adad-d149a4e935df.png)

**Comment by gsegit** [comment]
Jup, hast recht, das macht mehr Sinn ;D

**Comment by iakmds** [comment]
Neue Version ist da - nun kann ich das Issue schließen :smile:
