### ISSUE TITLE
[BUG] Shellexeption

### ISSUE THREAD

**Issue by gsegit** [iakmds/buhocms#4]
Hallo ;D
Ich kriege die Meldung Shellexeption ,,, Leider kann ich zu dem nicht viel schreiben, ausser das ich den public ordner geöffnet hab. Danach ist die Meldung aufgetaucht. 

Hab ein Screenshot gemacht ;D
![Bildschirmfoto vom 2023-03-02 22-10-20](https://user-images.githubusercontent.com/104396251/222555676-260aee55-5e5e-4c44-ab40-d98382bbfa84.png)

Mir sind noch ein paar Sachen aufgefallen, aber die schreibe ich in einem extra post ;D

Tschöö
Bogus

**Comment by iakmds** [comment]
Ich glaube, das Starten/Stoppen eines Servers funktioniert in dieser Version nicht ganz richtig, habe den fix dafür gefunden. Ich schreibe dir hier nochmal, wenn die neue Version raus ist, vielleicht wird sie diesen Fehler behoben haben

**Comment by gsegit** [comment]
Ich kann das Programm selbst kompillieren, also wenn du den Fix eingebunden hast, werde ich den Code übersetzen und schaun ob es dann besser geht ;D

Nur, vielleicht ein Merkmal reinschreiben in der Info, das man weiss das es ne andere Version ist ;D Muss ja nicht die Versionnummer selbst sein, kann einfach nur irgendwie was stehen, wie Version von Datum .. z.B.;

**Comment by iakmds** [comment]
Ich lade hier mal das bundle hoch, da musst du nichts installieren, einfach nur extrahieren und die `buhocms` Datei öffnen  :+1:

[bundle.tar.gz](https://github.com/iakmds/buhocms/files/10888061/bundle.tar.gz)

**Comment by gsegit** [comment]
OK, bug ist gefixt ;D Ich schliesse mal ;D
